# spring.application.name=alert-read-service

# spring.datasource.url=jdbc:postgresql://localhost:5432/alertdb
# spring.datasource.username=postgres
# spring.datasource.password=admin

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.application.name=alert-read-service

server.port=8080

spring.datasource.url=jdbc:h2:mem:alertdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console