#Trying to connect the postgres in VM but permission denied
# spring.application.name=alert-read-service
#
# spring.datasource.url=jdbc:postgresql://10.161.5.175:5432/monitoring_db
# spring.datasource.username=postgres
# spring.datasource.password=admin
#
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# H2 Memory
#spring.application.name=alert-read-service
#
#server.port=8080
#
#spring.datasource.url=jdbc:h2:mem:alertdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console



spring.application.name=alert-read-service

server.port=8089

spring.datasource.url=jdbc:postgresql://10.161.5.175:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect