spring:
  application:
    name: SNMPTrapMicroservice

  datasource:
    url: jdbc:postgresql://10.161.5.175:5432/snmptrapdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

snmp:
  target:
    host: 127.0.0.1
  trap:
    port: 162
    community: public
    enabled: true

simulator:
  enabled: false
  trap:
    interval: 5000

logging:
  level:
    com.example.snmptrapmicroservice: DEBUG
    org.snmp4j: WARN
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always