spring:
  application:
    name: AlarmsEventsService
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



snmp:
  url: "http://localhost:8080/"
  trap:
    url: "http://localhost:8085/api/traps"

producer:
  kafka:
    service: "http://localhost:8081/"


server:
  port: 8084