spring.application.name=SnmpMicroservice-1
server.port=8080
server.address=0.0.0.0

# SNMP Configuration
snmp.manager.host=localhost
snmp.manager.port=161
snmp.community.public=public
snmp.timeout=3000
snmp.retries=3

snmp.scheduler.enabled: true
snmp.scheduler.interval: 30000


# Alert Thresholds
alert.cpu.threshold=80
alert.memory.threshold=85

# Use simulator mode (set to false for real SNMP manager)
snmp.simulator.enabled=true

# Logging
logging.level.com.example.snmpmicroservice=DEBUG
logging.level.org.snmp4j=WARN
snmp.allowed-hosts=server1,router1,switch

