apiVersion: v1
kind: Service
metadata:
  name: alarmseventsservice
spec:
  type: NodePort
  selector:
    app: alarmseventsservice
  ports:
    - protocol: TCP
      port: 8084        # service port
      targetPort: 8084  # container port
      nodePort: 30094   # external port (you can change if needed)