apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarmseventsservice
  labels:
    app: alarmseventsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarmseventsservice
  template:
    metadata:
      labels:
        app: alarmseventsservice
    spec:
      containers:
        - name: metricsalerts-container
          image: 10.161.5.175:5000/alarmseventsservice:8
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "10.161.5.175:9092"
