apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-read-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-read
  template:
    metadata:
      labels:
        app: alert-read
    spec:
      containers:
        - name: alert-read-container
          image: 10.161.5.175:5000/alert-read-service:4
          imagePullPolicy: Always
          ports:
            - containerPort: 8089