apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-kafka-service
  labels:
    app: consumer-kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-kafka-service
  template:
    metadata:
      labels:
        app: consumer-kafka-service
    spec:
      containers:
        - name: consumer-kafka-service
          image: 10.161.5.175:5000/consumer-kafka-service:7
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: 10.161.5.175:9092
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: group_id
            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: earliest