apiVersion: v1
kind: Service
metadata:
  name: customer-plan-management
spec:
  selector:
    app: customer-plan-management
  type: NodePort
  ports:
    - protocol: TCP
      port: 9096
      targetPort: 9096
      nodePort: 30098