apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-plan-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-plan-management
  template:
    metadata:
      labels:
        app: customer-plan-management
    spec:
      containers:
        - name: customer-plan-management-container
          image: 10.161.5.175:5000/customer-plan-management:1
          imagePullPolicy: Always
          ports:
            - containerPort: 9096