apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-container
          image: 10.161.5.175:5000/kafka-producer:1.0
          imagePullPolicy: Always   # since using local image
          ports:
            - containerPort: 8083
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "10.161.5.175:9092"