apiVersion: v1
kind: Service
metadata:
  name: snmp-trap-service
spec:
  type: NodePort
  selector:
    app: snmp-trap-service
  ports:
    - protocol: TCP
      port: 8085        # service port
      targetPort: 8085  # container port
      nodePort: 30093   # external port