apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-trap-service
  labels:
    app: snmp-trap-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-trap-service
  template:
    metadata:
      labels:
        app: snmp-trap-service
    spec:
      containers:
        - name: trapservice-container
          image: 10.161.5.175:5000/snmp-trap-service:9
          imagePullPolicy: Always   # local image
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"
