apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
        - name: usermanagement-container
          image: 10.161.5.175:5000/usermanagement:1
          imagePullPolicy: Always
          ports:
            - containerPort: 9991