spring:
  application:
    name: Consumer-Kafka-Service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:10.161.5.175:9092}

    consumer:
      group-id: metrics-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "*"

        spring.json.use.type.headers: false
        spring.json.value.default.type: com.hcl.Troy.DTO.RecommendationDTO

server:
  port: 8086